### ISSUE TITLE
Missing build-tool-depends on Hackage for 0.8.1.0

### ISSUE THREAD

**Issue by DanielG** [DanielG/cabal-helper#58]
We switched to `cabal-version: 2.0.0.0` and `build-type: simple` for 0.8.1.0 which sets cabal-install into a mode where it considers dependencies on components seperately. Hence cabal-helper-wrapper is no longer installed when depending only on the `cabal-helper` library.

Adding `build-tool-depends: cabal-helper:cabal-helper-wrapper` to the library component seems to fix this though "build-tool" is a bit of a misnormer here because we actually need the executable at runtime. Not sure if this is the proper thing to do in this case or not.

@hvr Hackage doesn't seem to let me add a `build-tool-depends` for 0.8.1.0 after the fact can could you add that for me?

PS: What's the proper procedure for asking for help from Hackage Trustees as a package maintainer? I don't really want to spam @hvr with these things exclusively :)

**Comment by DanielG** [comment]
Ugh, looks like the problem is worse than I thought. Cabal installs the components into seperate directories in the store so that `libexecdir` (from Paths_*) points at the wrong directory when compiling the library component and cabal-helper-wrapper can't be found.

This works locally of course because we have special path guessing logic for that since `libexecdir` is just plain wrong when installing inplace anyways :(

**Comment by hvr** [comment]
> Hackage doesn't seem to let me add a build-tool-depends for 0.8.1.0 after the fact can could you add that for me?

Currently I can't, because first I'd need to relax the revision-validation rules to allow adding intra-package dependencies... :-/

> Cabal installs the components into seperate directories in the store 

Yes, that was a huge improvement over the old scheme, as it allows to only build and register the components your build-plan really needs; but this requires having separate transactions, hence separate folders.

And well, I do seem to recall that I told you I was worried that when the `scope` feature was added, we hadn't taken into account the nix-style semantics of `new-build`...

> What's the proper procedure for asking for help from Hackage Trustees as a package maintainer?

Simply file something at https://github.com/haskell-infra/hackage-trustees/issues/new :-)

**Comment by DanielG** [comment]
Ok, I've added revisions for `0.8.1.{0,1}` with `base<0` and will be uploading a new patchlevel version with `build-type: Custom` shortly. That should fix things for now until we can get this fixed properly in Cabal.

**Comment by DanielG** [comment]
In master `cabal-helper-wrapper` was absorbed back into the library since it turned out it was just a historical vestige anyways. Hence this problem just goes away.
